[package]
name = "easy-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.15.1", features = ["renderer-skia"] }
chrono = { version = "0.4", default-features = false, features = ["serde", "clock", "std"] }
chrono-tz = "0.10.3"
rdev = "0.5.3"
log = "0.4.27"
flexi_logger = "0.23"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
tray-icon = "0.21.2"
# 正则表达式
regex = "1.12.2"
# 跨平台粘贴板库
arboard = "2"
clipboard-master = "4.0.0"
winit = "0.30.12"
# 用于访问 winit 特性（跟随slint版本）
i-slint-backend-winit = "1.15.1"
# 用于获取原始窗口句柄
raw-window-handle = "0.6"
# 用于调用 Windows 底层 API
windows-sys = { version = "0.52", features = ["Win32_Foundation", "Win32_System_DataExchange", "Win32_System_Memory", "Win32_System_Ole", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
single-instance = "0.3"
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.8.2"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[build-dependencies]
slint-build = "1.15.1"
# windows增加ico
winresource = "0.1"

[profile.dev]
opt-level = 1 
lto = "thin"

# release优化
[profile.release]
opt-level = "z"      # 优化文件体积
lto = true           # 开启全局链接优化
codegen-units = 1    # 牺牲编译速度换取更小的体积
panic = "abort"      # 移除异常回溯代码
strip = true         # 自动剥离符号表 (Rust 1.59+)
