import { TimeTrans } from "time_trans.slint";
import { HomeWindow } from "home.slint";
import { ClipboardHistoryWindow } from "clipboard_history.slint";
import { FilePreviewWindow } from "file_preview.slint";
import { TextTranslationWindow } from "text_translation.slint";
import { SettingsWindow } from "settings.slint";
import { ScreenshotWindow } from "screenshot.slint";
import { TopImageWindow } from "top_image.slint";

export { TimeTrans, HomeWindow, ClipboardHistoryWindow, FilePreviewWindow, TextTranslationWindow, SettingsWindow, ScreenshotWindow, TopImageWindow }
