import { LineEdit, VerticalBox, ComboBox, Button, Switch } from "std-widgets.slint";
import "../assets/font/NotoSans.ttf";

export component TimeTrans inherits Window {
    no-frame: true;
    always-on-top: true;
    width: 210px;
    height: 100px;
    background: transparent;
    default-font-family: "Noto Sans";

    // 定义变量
    in-out property <string> input_value: "";
    in-out property <string> result_value: "";
    in-out property <bool> timestamp_unit: false;
    // 当前时区下标
    in-out property <int> timezone_index: 0;
    // 当前时区
    in-out property <string> timezone_label: "";
    
    in-out property <int> close_time: 3;
    out property <bool> has_hover: false;
    in-out property <bool> has_copy: false;

    // 定义回调函数（rust函数）
    callback update_result(input: string, unit: bool, timezone_index: int);
    callback copy_to_clipboard(text: string);
    callback close_window();
    callback show_window();
    callback move_window();
    callback last_timezone(i: int);
    callback next_timezone(i: int);

    // 值变更回调
    changed input_value => {
        if (root.input_value != "") {
            update_result(root.input_value, root.timestamp_unit, root.timezone_index);
        }
    }
    changed timestamp_unit => {
        if (root.input_value != "") {
            update_result(root.input_value, root.timestamp_unit, root.timezone_index);
        }
    }
    changed timezone_index => {
        if (root.input_value != "") {
            update_result(root.input_value, root.timestamp_unit, root.timezone_index);
        }
    }
    changed result_value => {
        if (root.result_value != "Error" && root.result_value != "") {
            root.close_time = 3;
            show_window();
        }
    }

    // 定时器
    timer := Timer {
        interval: 1s;
        running: true;
        triggered() => {
            if (!root.has_hover && close_time > 0) {
                close_time -= 1;
                if (close_time == 0) {
                    root.close_window();
                    root.has_hover = false;
                    root.has_copy = false;
                    root.input_value = "";
                    root.result_value = "";
                }
            }
        }
    }
    // 触摸区
    area := TouchArea {
        width: root.width;
        height: root.height;
        enabled: true;
        moved => {
            root.move_window();
        }
        changed has_hover => {
            root.has_hover = true;
        }
    }

    // 子组件内容 2026-01-27 16:37:36
    Rectangle {
        width: root.width;
        height: root.height;
        border-radius: 8px;     // 圆角大小，按需调整
        border-width: 1px;
        border-color: #D1D1D1;
        background: rgba(255,255,255,0.95); // 可换成其它颜色或透明度
        clip: true;             // 裁切子元素到圆角区域

        VerticalLayout {
            padding: 5px;
            spacing: 2px;

            HorizontalLayout {
                spacing: 2px;
                VerticalBox {
                    padding: 2px;
                    LineEdit {
                        placeholder-text: "输入时间戳或时间字符串";
                        text <=> root.input_value;
                    }
                }

                // 关闭按钮
                Rectangle {
                    width: 24px;
                    height: 22px;
                    background: touch.pressed ? #eee : touch.has-hover ? #f5f5f5 : transparent;
                    border-radius: 4px;

                    Text {
                        text: "×";
                        font-size: 18px;
                        // 核心居中属性
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }

                    touch := TouchArea {
                        clicked => {
                            root.close_window();
                            root.has_hover = false;
                            root.has_copy = false;
                            root.input_value = "";
                            root.result_value = "";
                        }
                    }
                }
            }

            HorizontalLayout {
                spacing: 2px;

                Switch {
                    width: 75px;
                    text: self.checked ? "ms" : "s";
                    checked <=> timestamp_unit;
                }

                HorizontalLayout {
                    spacing: 2px;

                    Button {
                        height: 25px;
                        text: "<";
                        clicked => {
                            root.last_timezone(root.timezone_index);
                        }
                    }

                    Text {
                        text: root.timezone_label;
                        width: 50px;
                        horizontal-alignment: left;
                        vertical-alignment: center;
                    }

                    Button {
                        height: 25px;
                        text: ">";
                        clicked => {
                            root.next_timezone(root.timezone_index);
                        }
                    }
                }
            }

            HorizontalLayout {
                spacing: 2px;

                Text {
                    font-size: 14px;
                    font-weight: 700;
                    color: #3B5998;
                    text: root.result_value;
                    horizontal-stretch: 1;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                Button {
                    width: 55px;
                    height: 25px;
                    text: root.has_copy?"Done":"Copy";
                    enabled: root.result_value != "";
                    clicked => {
                        copy_to_clipboard(root.result_value);
                        root.has_copy = true;
                    }
                }
            }

        }
    }
}
