import { LineEdit, VerticalBox, ComboBox, Button, Switch } from "std-widgets.slint";
import { CloseButton } from "components/close.slint";

export component TimeTrans inherits Window {
    no-frame: true;
    always-on-top: true;
    width: 210px;
    height: 100px;
    background: transparent;

    // 定义变量
    in-out property <string> input_value: "2006-01-02 15:04:05";
    in-out property <string> result_value: "2006-01-02 15:04:05";
    in-out property <bool> timestamp_unit: false;
    in-out property <int> timezone_index: 0;
    in-out property <int> close_time: 3;
    property <[string]> timezones: [
        "Asia/Shanghai",
        "UTC",
        "America/New_York",
        "America/Los_Angeles",
        "Europe/London",
        "Asia/Tokyo"
    ];
    property <[string]> timezone_labels: [
        "CST/+8",
        "UTC/+0",
        "EST/-5",
        "PST/-8",
        "GMT/+0",
        "JST/+9"
    ];
    property <bool> has-hover: false;

    // 定义回调函数（rust函数）
    callback update_result(input: string, unit: bool, timezone: string);
    callback copy_to_clipboard(text: string);
    callback close_window();

    // 值变更回调
    changed input_value => {
        update_result(root.input_value, root.timestamp_unit, root.timezones[root.timezone_index]);
    }
    changed timestamp_unit => {
        update_result(root.input_value, root.timestamp_unit, root.timezones[root.timezone_index]);
    }
    changed timezone_index => {
        update_result(root.input_value, root.timestamp_unit, root.timezones[root.timezone_index]);
    }

    // 定时器
    timer := Timer {
        interval: 1s;
        running: true;
        triggered() => {
            if (!root.has-hover && close_time > 0) {
                close_time -= 1;
                if (close_time == 0) {
                    root.close_window();
                    root.has-hover = false;
                }
            }
        }
    }
    // 触摸区
    area := TouchArea {
        width: root.width;
        height: root.height;
        enabled: true;
        changed has-hover => {
            root.has-hover = true;
        }
    }

    // 子组件内容
    Rectangle {
        width: root.width;
        height: root.height;
        border-radius: 8px;     // 圆角大小，按需调整
        background: rgba(255,255,255,0.95); // 可换成其它颜色或透明度
        clip: true;             // 裁切子元素到圆角区域

        VerticalLayout {
            padding: 5px;
            spacing: 2px;

            HorizontalLayout {
                spacing: 2px;
                VerticalBox {
                    padding: 2px;
                    LineEdit {
                        placeholder-text: "输入时间戳或时间字符串";
                        text <=> root.input_value;
                    }
                }

                CloseButton {
                    clicked => {
                        root.close_window();
                        root.has-hover = false;
                    };
                }
            }

            HorizontalLayout {
                spacing: 2px;

                Switch {
                    width: 75px;
                    text: self.checked ? "ms" : "s";
                    checked <=> timestamp_unit;
                }

                HorizontalLayout {
                    spacing: 2px;

                    Button {
                        height: 25px;
                        text: "<";
                        clicked => {
                            if root.timezone_index == 0 {
                                root.timezone_index = root.timezones.length - 1;
                            } else {
                                root.timezone_index -= 1;
                            }
                        }
                    }

                    Text {
                        text: timezone_labels[root.timezone_index];
                        width: 50px;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }

                    Button {
                        height: 25px;
                        text: ">";
                        clicked => {
                            if root.timezone_index >= root.timezones.length - 1 {
                                root.timezone_index = 0;
                            } else {
                                root.timezone_index += 1;
                            }
                        }
                    }
                }
            }

            HorizontalLayout {
                spacing: 2px;

                Text {
                    font-size: 14px;
                    font-weight: 700;
                    color: blue;
                    text: root.result_value;
                    horizontal-stretch: 1;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                Button {
                    width: 55px;
                    height: 25px;
                    text: "Copy";
                    enabled: root.result_value != "";
                    clicked => copy_to_clipboard(root.result_value);
                }
            }

        }
    }
}
